# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43db89423f63a02a2d2185f697e9b198b0e749bd18ed6aee8f56984f094867800a9587e3fdb6fa02957cd2c77500c1f3f636a352a1bf9463746570596747c9c4

test:
  secret_key_base: c345883b5ae9811695e0488f5e39bd5009c27b8cf519763ff5197be6bec298aaa1eae9ce363ea48e02e2334a796bfcee2ced8d819c3424ea4a1eda2c39869410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
